### ISSUE TITLE
PNG format cannot be forced

### ISSUE THREAD

**Issue by ImaneAcherrat** [darbaoui/laravel-ui-avatars#2]
The default avatar format depends on the header accept value if the format is not specified in the URL. If the Accept header includes `image/svg+xml`, the returned image type will be SVG.

- UI avatars documentation

<img width="400" alt="Screenshot 2022-10-24 at 16 53 16" src="https://user-images.githubusercontent.com/86793660/197570429-9ded7a13-43a9-48f1-9555-29a2a6465ab2.png">

- UI avatars code

<img width="600" alt="Screenshot 2022-10-24 at 15 40 34" src="https://user-images.githubusercontent.com/86793660/197570473-23b8b08d-1408-4683-9c4c-9593678adf37.png">

**Comment by darbaoui** [comment]
Fix https://github.com/darbaoui/laravel-ui-avatars/commit/4f72d7135cc19b08394945f60ca28da94797bfd1
